### ISSUE TITLE
'TickTick access token is invalid'

### ISSUE THREAD

**Issue by Hammuts** [mxschll/logseq-ticktick-plugin#2]
First of all, awesome to see a ticktick plugin! A new place for me to capture tasks is always welcome.

However, after following the instructions and entering the credentials in the settings in Logseq, I am told that the Ticktick access token is invalid whenever I try to use the command. I tried it a couple of more times with different access codes, but to no avail.

![CleanShot 2023-04-12 at 10 59 55](https://user-images.githubusercontent.com/58487195/231407840-ce89e239-95de-4433-ae0f-5fdf79a81cc8.png)

Any idea what the problem might be?

**Comment by mxschll** [comment]
Hi @Hammerpawn,

Thank you. Unfortunately I had to find out that there is a difference in using fetch() when the plugin is loaded as "unpacked plugin" or loaded via the Logseq marketplace, see #1 

The only solution I can think of right now is to retrieve the access token outside Logseq. I will implement a solution today and write a tutorial on how to retrieve the TickTick token. I'll let you know when it's done :)

**Comment by Hammuts** [comment]
@mxschll Gotcha, perfect! :-)

**Comment by mxschll** [comment]
@Hammerpawn I created a workaround. After updating the plugin, you have to set the TickTick access token in the plugin settings. You can use [this site](https://mxschll.github.io/logseq-ticktick-plugin) to retrieve it.

Let me know, if something doesn't work :)
